### ISSUE TITLE
No Voltage for AMD Ryzen 5950x

### ISSUE THREAD

**Issue by InvaderDolan** [Ta180m/zenmonitor3#6]
Hi. Firstly, I installed the original zenpower and zenmonitor and then saw that they don't have Zen 3 support. After that I found your fork and was very happy until I saw that I still can't find the voltage of the CPU because exactly this I wanted to test during stress tests.
![image](https://user-images.githubusercontent.com/19179207/129458014-1f7c4ba6-7a68-47c3-a8c2-efeec1d15710.png)

Thank you!

**Comment by KeithMyers** [comment]
Hmmm, strange.
You should have all the normal sensor values.
I have all the values, including cpu voltage and soc voltage.
![Screenshot from 2021-08-14 12-28-52](https://user-images.githubusercontent.com/31547850/129458172-b880d8ce-317f-43f9-87f4-d86f923177ae.png)

**Comment by InvaderDolan** [comment]
@KeithMyers what do you recommend to do? lm_sensors don't work too.

**Comment by KeithMyers** [comment]
I'd uninstall the module, reboot and try installing again.

**Comment by InvaderDolan** [comment]
@KeithMyers I uninstalled everything. Rebooted. Installed again. Forgot to activate module on zenpower3. Activated module. Reboot and everything works now :) Thank you!

**Comment by KeithMyers** [comment]
Glad to help and hear the app is working for you now.
