### ISSUE TITLE
No Temperature in R5 5600H

### ISSUE THREAD

**Issue by aviezab** [Ta180m/zenmonitor3#7]
Dear @Ta180m 
I am using zenpower3 from You and loaded `zenpower3` with modprobe,  yet there is no temperature shown.
![image](https://user-images.githubusercontent.com/34294278/138312706-be2265c9-0976-4820-9aad-8aeb6af988fd.png)
![image](https://user-images.githubusercontent.com/34294278/138312949-0b3ae6aa-7f6c-43b9-a876-93e2a2a5b7ad.png)

Can You elaborate with me to fix this issue?

**Comment by Ta180m** [comment]
Cezanne support for CPUs like the 5600H is currently a work-in-progress, as you can see in [this issue](https://github.com/Ta180m/zenpower3/issues/2). I don't have a Cezanne CPU to test anything, so it would be great if you could provide some [debug data](https://github.com/ocerman/zenpower/issues/12).

**Comment by Ta180m** [comment]
Cezanne support was added in Zenpower3 v0.2.0. @aviezab zenmonitor3 should work now with your CPU.

**Comment by aviezab** [comment]
Great, it is working now, Thanks Anthony Wang! 😄
