### ISSUE TITLE
Running on Proxmox (debian buster) give the following failure.

### ISSUE THREAD

**Issue by cooljimy84** [Ta180m/zenmonitor3#9]
So proxmox has no gui, its jus the terminal. I thought this used N-curses when it doesn't find a gui.

```
root@pve1:~/zenmonitor3# sudo ./zenmonitor
Unable to init server: Could not connect: Connection refused
option parsing failed: Cannot open display: 
```

**Comment by Ta180m** [comment]
To use the Zenmonitor CLI, you must compile and install it with `make build-cli && sudo make install`.
